### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by CarmenMartinezSeijas** [fmalmeida/bacannot#102]
Dear Mr. Almeida,

I've seen that you have recently closed a summary issue related to .json file. I was wondering if there is any possibility of having a summary for each individual tool. For example, Bacannot analyzes resistance with AMRFinderPlus, ARGMiner and RGI and we have the results from this tools in individual files for each strain, but we don't have a summary of AMRFinderPlus (or other tool) results for all the strains so you can compare them to each other in terms of resistance. Is there any possibility to do so or that you can include it? Because i thought of collapsing all the files from each tool in one, but not every file has the ID of the strain.

Thanks for developing these tool. It has been really helpful.

Thanks in advance,

Carmen.

**Comment by fmalmeida** [comment]
Hi @CarmenMartinezSeijas ,
If I understood correctly, you mean having a single `summary` file, with all the annotations of all samples together, right?

If so, the pipeline should already create a file called `bacannot_summary.json` that is placed in the root of the `params.output` directory.

The file should look like an amalgamation of all the results of all samples that were used as input for the pipeline run:

```console
{
  "sample_1": { ... everything ... },
  "sample_2": { ... everything ... }.
  ...
}
```

Is this file missing? If yes, we need to investigate. If not, I ask whether this is the file you are mentioning/requesting.

**Comment by fmalmeida** [comment]
If this concatenated file is present, one can query, compare, parse, and subset based on any argument / key like sample id, tool, gene, etc, using the `jq` tool for example: https://github.com/maroskukan/jq-cookbook

Is that what you mean, or you mean something more specific?

**Comment by fmalmeida** [comment]
Another option, which I have been using recently is, loading the concatenated json file in R, as a R object that can be easily subsetted, and used for generating heatmap plots for example, having the sample names as rows, and gene names (or classes as columns), using the following libraries:

```R

#
# load libraries
#
library(jsonlite)
library(stringr)
library(dplyr)

#
# read annotation summary file
#
summary_file <-
    read_json( opt$input )
samples <-
    names( summary_file ) # get available samples in file

```

Then, you will see that the summary_file object has lots of keys, that can be used for subsetting and plotting 😄

**Comment by CarmenMartinezSeijas** [comment]
> If this concatenated file is present, one can query, compare, parse, and subset based on any argument / key like sample id, tool, gene, etc, using the `jq` tool for example: https://github.com/maroskukan/jq-cookbook
> 
> `jq` tool manual: https://jqlang.github.io/jq/
> 
> Is that what you mean, or you mean something more specific?

Hi @fmalmeida,

I have the bacannot_summary.json file, but I wasn't sure how to query, compare, parse, and subset the info contained in that file. I will tell my lab mate @josefdiaz to run it, because I know very little about bioinformatics.

Thank you so much for your help,

Carmen

**Comment by fmalmeida** [comment]
That is alright!

Personally, I suggest trying the latest suggestion, using R to load the summary as an R object with the function `read_json`. I generally find it easy to query and plot once in R.

One thing I can share is that, currently, I have a work under development which is to provide a tool for comparing the samples' results provided by `bacannot`. The idea would be an external tool that could be executed after the pipeline is finished.

However, this is still in progress, and due to alternating project focus, it may take a while until version 1.0 is ready for users.

So, until then, the R option or `jq` are my best recommendations.

Since this is not pipeline-wise, I will close this issue. However, if you believe find a problem with the file, or with parsing it, etc, please feel free to re-open it or open a new one.

If you just have troubles or would like to ask guidance on how to query it, you can make contact through my email since it is something non-pipeline-wise.

Finally, if while playing with the tool, you figure out a script, or a step that could be added to the pipeline and would like to share & contribute, it would be more than welcomed!

Kind regards,
Felipe.
