### ISSUE TITLE
Wrap-up `dev` and release v3.3

### ISSUE THREAD

**Issue by fmalmeida** [fmalmeida/bacannot#88]
Wrap up all the work in dev branch and release v3.3.

Needs:

- [x] #50 
- [x] #69 
- [x] #81 
- [x] #85 
- [ ] #30 (Maybe)
- [x] #98
- [x] #100 
- [x] #102 
- [x] #104 
- [x] #107 
- [x] Run test with docker
- [x] Run test with singularity 
- [x] Is db download working with singularity?
- [x] Update documentation
- [x] Push all docker images

**Comment by fmalmeida** [comment]
I think now the pipeline is ready for new release.

Should do a few executions to test and review the docs.

**Comment by fmalmeida** [comment]
Must try to include #95 ; #57 and #30 ?

**Comment by josefdiaz** [comment]
Hello,
I have worked with my colleague @CarmenMartinezSeijas and we have tried to run dev-version and we try that command and we have the next message
`./nextflow run fmalmeida/bacannot     --input bacannot_samplesheet.yaml     --output Resultadosconejosdev     --bacannot_db ./bacannot_db_2023   --max_memory 100.GB    -profile docker -r dev-latest
N E X T F L O W  ~  version 23.04.3
Project `fmalmeida/bacannot` contains uncommitted changes -- Cannot switch to revision: dev-latest
`
Thanks

**Comment by fmalmeida** [comment]
It is missing a white space after dev,

Should be -r dev -latest and not -r dev-latest

;)

**Comment by josefdiaz** [comment]
We try right now and we get that
/nextflow run fmalmeida/bacannot     --input bacannot_samplesheet.yaml     --output Resultadosconejosdev     --bacannot_db ./bacannot_db_2023   --max_memory 100.GB    -profile docker -r dev -latest 
N E X T F L O W  ~  version 23.04.3
Pulling fmalmeida/bacannot ...
fmalmeida/bacannot contains uncommitted changes -- cannot pull from repository

**Comment by fmalmeida** [comment]
Probably because this branch was deleted.

Do this before running:


rm -rf ~/.nextflow/assets/fmalmeida/bacannot

Normally it is installed in the home dir, but if not, please correct the
above path.

**Comment by josefdiaz** [comment]
Hello,
I have tried to run the pipeline after the previous fixes and I get that:
`./nextflow run fmalmeida/bacannot --input bacannot_samplesheet.yaml --output Resultadosconejosdev --bacannot_db ./bacannot_db_2023 --max_memory 100.GB -profile docker -r dev -latest                                                                                                                                                        
N E X T F L O W  ~  version 23.04.3                                                                                                                                                    
Pulling fmalmeida/bacannot ...                                                                                                                                                         
 Already-up-to-date                                                                                                                                                                    
Launching `https://github.com/fmalmeida/bacannot` [exotic_mestorf] DSL2 - revision: 1ed4a8e4c4 [dev]                                                                                   
                                                                                                                                                                                       
                                                                                                                                                                                       
------------------------------------------------------
  fmalmeida/bacannot v3.3
------------------------------------------------------
Core Nextflow options
  revision       : dev
  runName        : exotic_mestorf
  containerEngine: docker
  launchDir      : /home/jfrancisco
  workDir        : /home/jfrancisco/work
  projectDir     : /home/jfrancisco/.nextflow/assets/fmalmeida/bacannot
  userName       : jfrancisco
  profile        : docker
  configFiles    : /home/jfrancisco/.nextflow/assets/fmalmeida/bacannot/nextflow.config

Input/output options
  input          : bacannot_samplesheet.yaml
  output         : Resultadosconejosdev
  bacannot_db    : ./bacannot_db_2023

Max job request options
  max_memory     : 100.GB

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use fmalmeida/bacannot for your analysis please cite:

* The pipeline
  https://doi.org/10.5281/zenodo.3627669

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/fmalmeida/bacannot/blob/master/CITATIONS.md
------------------------------------------------------
executor >  local (7)
[-        ] process > BACANNOT:UNICYCLER            -
[-        ] process > BACANNOT:FLYE                 -
[1f/61f49e] process > BACANNOT:PROKKA (sample_2445) [  0%] 0 of 90
[-        ] process > BACANNOT:MLST                 -
[-        ] process > BACANNOT:BARRNAP              -
[-        ] process > BACANNOT:COMPUTE_GC           -
[-        ] process > BACANNOT:KOFAMSCAN            -
[-        ] process > BACANNOT:KEGG_DECODER         -
[-        ] process > BACANNOT:PLASMIDFINDER        -
[-        ] process > BACANNOT:PLATON               -
[-        ] process > BACANNOT:MOBSUITE             -
[-        ] process > BACANNOT:ISLANDPATH           -
[-        ] process > BACANNOT:INTEGRON_FINDER      -
[-        ] process > BACANNOT:INTEGRON_FINDER_2GFF -
[-        ] process > BACANNOT:VFDB                 -
[-        ] process > BACANNOT:VICTORS              -
[-        ] process > BACANNOT:PHAST                -
[-        ] process > BACANNOT:PHIGARO              -
[-        ] process > BACANNOT:PHISPY               -
[-        ] process > BACANNOT:ICEBERG              -
[-        ] process > BACANNOT:AMRFINDER            -
[-        ] process > BACANNOT:CARD_RGI             -
[-        ] process > BACANNOT:ARGMINER             -
[-        ] process > BACANNOT:RESFINDER            -
[-        ] process > BACANNOT:CALL_METHYLATION     -
[-        ] process > BACANNOT:REFSEQ_MASHER        -
[-        ] process > BACANNOT:DIGIS                -
[-        ] process > BACANNOT:ANTISMASH            -
[-        ] process > BACANNOT:SEQUENCESERVER       -
[-        ] process > BACANNOT:MERGE_ANNOTATIONS    -
[-        ] process > BACANNOT:DRAW_GIS             -
[-        ] process > BACANNOT:GFF2GBK              -
[-        ] process > BACANNOT:CREATE_SQL           -
[-        ] process > BACANNOT:JBROWSE              -
[-        ] process > BACANNOT:REPORT               -
[-        ] process > BACANNOT:SUMMARY              -
[-        ] process > BACANNOT:MERGE_SUMMARIES      -
[-        ] process > BACANNOT:CIRCOS               -
ERROR ~ Error executing process > 'BACANNOT:PROKKA (sample_2554)'

Caused by:
  Missing output file(s) `annotation` expected by process `BACANNOT:PROKKA (sample_2554)`

Command executed:

  #!/usr/bin/env bash
  
  # save prokka version
  prokka -v &> prokka_version.txt ;
  
  # where are default prokka dbs?
  dbs_dir=$(prokka --listdb 2>&1 >/dev/null |  grep "databases in" | cut -f 4 -d ":" | tr -d " ") ;
  
  # get hmms that shall be used
  # PGAP contains TIGRFAM hmm models. When not skipping PGAP, TIGRFAM is not loaded.
  cp -r $dbs_dir prokka_db
  cp bacannot_db_2023/prokka_db/TIGRFAMs_15.0.hmm prokka_db/hmm
  
  # hmmpress
  ( cd  prokka_db/hmm/ ; for i in *.hmm ; do hmmpress -f $i ; done )
  
  # clean headers char limit
  awk '{ if ($0 ~ />/) print substr($0,1,21) ; else print $0 }'  > cleaned_header.fasta
  
  # run prokka
  prokka \
      --dbdir prokka_db \
         \
executor >  local (7)
[-        ] process > BACANNOT:UNICYCLER            -
[-        ] process > BACANNOT:FLYE                 -
[6e/39b261] process > BACANNOT:PROKKA (sample_2429) [  3%] 3 of 90, failed: 3
[-        ] process > BACANNOT:MLST                 -
[-        ] process > BACANNOT:BARRNAP              -
[-        ] process > BACANNOT:COMPUTE_GC           -
[-        ] process > BACANNOT:KOFAMSCAN            -
[-        ] process > BACANNOT:KEGG_DECODER         -
[-        ] process > BACANNOT:PLASMIDFINDER        -
[-        ] process > BACANNOT:PLATON               -
[-        ] process > BACANNOT:MOBSUITE             -
[-        ] process > BACANNOT:ISLANDPATH           -
[-        ] process > BACANNOT:INTEGRON_FINDER      -
[-        ] process > BACANNOT:INTEGRON_FINDER_2GFF -
[-        ] process > BACANNOT:VFDB                 -
[-        ] process > BACANNOT:VICTORS              -
[-        ] process > BACANNOT:PHAST                -
[-        ] process > BACANNOT:PHIGARO              -
[-        ] process > BACANNOT:PHISPY               -
[-        ] process > BACANNOT:ICEBERG              -
[-        ] process > BACANNOT:AMRFINDER            -
[-        ] process > BACANNOT:CARD_RGI             -
[-        ] process > BACANNOT:ARGMINER             -
[-        ] process > BACANNOT:RESFINDER            -
[-        ] process > BACANNOT:CALL_METHYLATION     -
[-        ] process > BACANNOT:REFSEQ_MASHER        -
[-        ] process > BACANNOT:DIGIS                -
[-        ] process > BACANNOT:ANTISMASH            -
[-        ] process > BACANNOT:SEQUENCESERVER       -
[-        ] process > BACANNOT:MERGE_ANNOTATIONS    -
[-        ] process > BACANNOT:DRAW_GIS             -
[-        ] process > BACANNOT:GFF2GBK              -
[-        ] process > BACANNOT:CREATE_SQL           -
[-        ] process > BACANNOT:JBROWSE              -
[-        ] process > BACANNOT:REPORT               -
[-        ] process > BACANNOT:SUMMARY              -
[-        ] process > BACANNOT:MERGE_SUMMARIES      -
[-        ] process > BACANNOT:CIRCOS               -
Execution cancelled -- Finishing pending tasks before exit
ERROR ~ Error executing process > 'BACANNOT:PROKKA (sample_2554)'

Caused by:
  Missing output file(s) `annotation` expected by process `BACANNOT:PROKKA (sample_2554)`

Command executed:

  #!/usr/bin/env bash
  
  # save prokka version
  prokka -v &> prokka_version.txt ;
  
  # where are default prokka dbs?
  dbs_dir=$(prokka --listdb 2>&1 >/dev/null |  grep "databases in" | cut -f 4 -d ":" | tr -d " ") ;
  
  # get hmms that shall be used
  # PGAP contains TIGRFAM hmm models. When not skipping PGAP, TIGRFAM is not loaded.
  cp -r $dbs_dir prokka_db
  cp bacannot_db_2023/prokka_db/TIGRFAMs_15.0.hmm prokka_db/hmm
  
  # hmmpress
  ( cd  prokka_db/hmm/ ; for i in *.hmm ; do hmmpress -f $i ; done )
  
  # clean headers char limit
  awk '{ if ($0 ~ />/) print substr($0,1,21) ; else print $0 }'  > cleaned_header.fasta
  
  # run prokka
  prokka \
      --dbdir prokka_db \
         \
executor >  local (7)
[-        ] process > BACANNOT:UNICYCLER            -
[-        ] process > BACANNOT:FLYE                 -
[c6/065629] process > BACANNOT:PROKKA (sample_2454) [  6%] 6 of 90, failed: 6
[-        ] process > BACANNOT:MLST                 -
[-        ] process > BACANNOT:BARRNAP              -
[-        ] process > BACANNOT:COMPUTE_GC           -
[-        ] process > BACANNOT:KOFAMSCAN            -
[-        ] process > BACANNOT:KEGG_DECODER         -
[-        ] process > BACANNOT:PLASMIDFINDER        -
[-        ] process > BACANNOT:PLATON               -
[-        ] process > BACANNOT:MOBSUITE             -
[-        ] process > BACANNOT:ISLANDPATH           -
[-        ] process > BACANNOT:INTEGRON_FINDER      -
[-        ] process > BACANNOT:INTEGRON_FINDER_2GFF -
[-        ] process > BACANNOT:VFDB                 -
[-        ] process > BACANNOT:VICTORS              -
[-        ] process > BACANNOT:PHAST                -
[-        ] process > BACANNOT:PHIGARO              -
[-        ] process > BACANNOT:PHISPY               -
[-        ] process > BACANNOT:ICEBERG              -
[-        ] process > BACANNOT:AMRFINDER            -
[-        ] process > BACANNOT:CARD_RGI             -
[-        ] process > BACANNOT:ARGMINER             -
[-        ] process > BACANNOT:RESFINDER            -
[-        ] process > BACANNOT:CALL_METHYLATION     -
[-        ] process > BACANNOT:REFSEQ_MASHER        -
[-        ] process > BACANNOT:DIGIS                -
[-        ] process > BACANNOT:ANTISMASH            -
[-        ] process > BACANNOT:SEQUENCESERVER       -
[-        ] process > BACANNOT:MERGE_ANNOTATIONS    -
[-        ] process > BACANNOT:DRAW_GIS             -
[-        ] process > BACANNOT:GFF2GBK              -
[-        ] process > BACANNOT:CREATE_SQL           -
[-        ] process > BACANNOT:JBROWSE              -
[-        ] process > BACANNOT:REPORT               -
[-        ] process > BACANNOT:SUMMARY              -
[-        ] process > BACANNOT:MERGE_SUMMARIES      -
[-        ] process > BACANNOT:CIRCOS               -
Execution cancelled -- Finishing pending tasks before exit
ERROR ~ Error executing process > 'BACANNOT:PROKKA (sample_2554)'

Caused by:
  Missing output file(s) `annotation` expected by process `BACANNOT:PROKKA (sample_2554)`

Command executed:

  #!/usr/bin/env bash
  
  # save prokka version
  prokka -v &> prokka_version.txt ;
  
  # where are default prokka dbs?
  dbs_dir=$(prokka --listdb 2>&1 >/dev/null |  grep "databases in" | cut -f 4 -d ":" | tr -d " ") ;
  
  # get hmms that shall be used
  # PGAP contains TIGRFAM hmm models. When not skipping PGAP, TIGRFAM is not loaded.
  cp -r $dbs_dir prokka_db
  cp bacannot_db_2023/prokka_db/TIGRFAMs_15.0.hmm prokka_db/hmm
  
  # hmmpress
  ( cd  prokka_db/hmm/ ; for i in *.hmm ; do hmmpress -f $i ; done )
  
  # clean headers char limit
  awk '{ if ($0 ~ />/) print substr($0,1,21) ; else print $0 }'  > cleaned_header.fasta
  
  # run prokka
  prokka \
      --dbdir prokka_db \
         \
executor >  local (7)
[-        ] process > BACANNOT:UNICYCLER            -
[-        ] process > BACANNOT:FLYE                 -
[1f/61f49e] process > BACANNOT:PROKKA (sample_2445) [  7%] 7 of 90, failed: 7
[-        ] process > BACANNOT:MLST                 -
[-        ] process > BACANNOT:BARRNAP              -
[-        ] process > BACANNOT:COMPUTE_GC           -
[-        ] process > BACANNOT:KOFAMSCAN            -
[-        ] process > BACANNOT:KEGG_DECODER         -
[-        ] process > BACANNOT:PLASMIDFINDER        -
[-        ] process > BACANNOT:PLATON               -
[-        ] process > BACANNOT:MOBSUITE             -
[-        ] process > BACANNOT:ISLANDPATH           -
[-        ] process > BACANNOT:INTEGRON_FINDER      -
[-        ] process > BACANNOT:INTEGRON_FINDER_2GFF -
[-        ] process > BACANNOT:VFDB                 -
[-        ] process > BACANNOT:VICTORS              -
[-        ] process > BACANNOT:PHAST                -
[-        ] process > BACANNOT:PHIGARO              -
[-        ] process > BACANNOT:PHISPY               -
[-        ] process > BACANNOT:ICEBERG              -
[-        ] process > BACANNOT:AMRFINDER            -
[-        ] process > BACANNOT:CARD_RGI             -
[-        ] process > BACANNOT:ARGMINER             -
[-        ] process > BACANNOT:RESFINDER            -
[-        ] process > BACANNOT:CALL_METHYLATION     -
[-        ] process > BACANNOT:REFSEQ_MASHER        -
[-        ] process > BACANNOT:DIGIS                -
[-        ] process > BACANNOT:ANTISMASH            -
[-        ] process > BACANNOT:SEQUENCESERVER       -
[-        ] process > BACANNOT:MERGE_ANNOTATIONS    -
[-        ] process > BACANNOT:DRAW_GIS             -
[-        ] process > BACANNOT:GFF2GBK              -
[-        ] process > BACANNOT:CREATE_SQL           -
[-        ] process > BACANNOT:JBROWSE              -
[-        ] process > BACANNOT:REPORT               -
[-        ] process > BACANNOT:SUMMARY              -
[-        ] process > BACANNOT:MERGE_SUMMARIES      -
[-        ] process > BACANNOT:CIRCOS               -
Execution cancelled -- Finishing pending tasks before exit
ERROR ~ Error executing process > 'BACANNOT:PROKKA (sample_2554)'

Caused by:
  Missing output file(s) `annotation` expected by process `BACANNOT:PROKKA (sample_2554)`

Command executed:

  #!/usr/bin/env bash
  
  # save prokka version
  prokka -v &> prokka_version.txt ;
  
  # where are default prokka dbs?
  dbs_dir=$(prokka --listdb 2>&1 >/dev/null |  grep "databases in" | cut -f 4 -d ":" | tr -d " ") ;
  
  # get hmms that shall be used
  # PGAP contains TIGRFAM hmm models. When not skipping PGAP, TIGRFAM is not loaded.
  cp -r $dbs_dir prokka_db
  cp bacannot_db_2023/prokka_db/TIGRFAMs_15.0.hmm prokka_db/hmm
  
  # hmmpress
  ( cd  prokka_db/hmm/ ; for i in *.hmm ; do hmmpress -f $i ; done )
  
  # clean headers char limit
  awk '{ if ($0 ~ />/) print substr($0,1,21) ; else print $0 }'  > cleaned_header.fasta
  
  # run prokka
  prokka \
      --dbdir prokka_db \
         \
executor >  local (7)
[-        ] process > BACANNOT:UNICYCLER            -
[-        ] process > BACANNOT:FLYE                 -
[1f/61f49e] process > BACANNOT:PROKKA (sample_2445) [  7%] 7 of 90, failed: 7
[-        ] process > BACANNOT:MLST                 -
[-        ] process > BACANNOT:BARRNAP              -
[-        ] process > BACANNOT:COMPUTE_GC           -
[-        ] process > BACANNOT:KOFAMSCAN            -
[-        ] process > BACANNOT:KEGG_DECODER         -
[-        ] process > BACANNOT:PLASMIDFINDER        -
[-        ] process > BACANNOT:PLATON               -
[-        ] process > BACANNOT:MOBSUITE             -
[-        ] process > BACANNOT:ISLANDPATH           -
[-        ] process > BACANNOT:INTEGRON_FINDER      -
[-        ] process > BACANNOT:INTEGRON_FINDER_2GFF -
[-        ] process > BACANNOT:VFDB                 -
[-        ] process > BACANNOT:VICTORS              -
[-        ] process > BACANNOT:PHAST                -
[-        ] process > BACANNOT:PHIGARO              -
[-        ] process > BACANNOT:PHISPY               -
[-        ] process > BACANNOT:ICEBERG              -
[-        ] process > BACANNOT:AMRFINDER            -
[-        ] process > BACANNOT:CARD_RGI             -
[-        ] process > BACANNOT:ARGMINER             -
[-        ] process > BACANNOT:RESFINDER            -
[-        ] process > BACANNOT:CALL_METHYLATION     -
[-        ] process > BACANNOT:REFSEQ_MASHER        -
[-        ] process > BACANNOT:DIGIS                -
[-        ] process > BACANNOT:ANTISMASH            -
[-        ] process > BACANNOT:SEQUENCESERVER       -
[-        ] process > BACANNOT:MERGE_ANNOTATIONS    -
[-        ] process > BACANNOT:DRAW_GIS             -
[-        ] process > BACANNOT:GFF2GBK              -
[-        ] process > BACANNOT:CREATE_SQL           -
[-        ] process > BACANNOT:JBROWSE              -
[-        ] process > BACANNOT:REPORT               -
[-        ] process > BACANNOT:SUMMARY              -
[-        ] process > BACANNOT:MERGE_SUMMARIES      -
[-        ] process > BACANNOT:CIRCOS               -
Execution cancelled -- Finishing pending tasks before exit
ERROR ~ Error executing process > 'BACANNOT:PROKKA (sample_2554)'

Caused by:
  Missing output file(s) `annotation` expected by process `BACANNOT:PROKKA (sample_2554)`

Command executed:

  #!/usr/bin/env bash
  
  # save prokka version
  prokka -v &> prokka_version.txt ;
  
  # where are default prokka dbs?
  dbs_dir=$(prokka --listdb 2>&1 >/dev/null |  grep "databases in" | cut -f 4 -d ":" | tr -d " ") ;
  
  # get hmms that shall be used
  # PGAP contains TIGRFAM hmm models. When not skipping PGAP, TIGRFAM is not loaded.
  cp -r $dbs_dir prokka_db
  cp bacannot_db_2023/prokka_db/TIGRFAMs_15.0.hmm prokka_db/hmm
  
  # hmmpress
  ( cd  prokka_db/hmm/ ; for i in *.hmm ; do hmmpress -f $i ; done )
  
  # clean headers char limit
  awk '{ if ($0 ~ />/) print substr($0,1,21) ; else print $0 }'  > cleaned_header.fasta
  
  # run prokka
  prokka \
      --dbdir prokka_db \
         \
      --outdir annotation \
      --cpus 4 \
      --mincontiglen 200 \
      --prefix sample_2554 \
      --genus '' \
      --species '' \
      --strain "sample_2554" \
      cleaned_header.fasta
  
  # remove tmp dir to gain space
  rm -r prokka_db

Command exit status:
  0

Command output:
  Working...    done.
  Pressed and indexed 1536 HMMs (1536 names).
  Models pressed into binary file:   HAMAP.hmm.h3m
  SSI index for binary model file:   HAMAP.hmm.h3i
  Profiles (MSV part) pressed into:  HAMAP.hmm.h3f
  Profiles (remainder) pressed into: HAMAP.hmm.h3p
  Working...    done.
  Pressed and indexed 4488 HMMs (4488 names and 4488 accessions).
  Models pressed into binary file:   TIGRFAMs_15.0.hmm.h3m
  SSI index for binary model file:   TIGRFAMs_15.0.hmm.h3i
  Profiles (MSV part) pressed into:  TIGRFAMs_15.0.hmm.h3f
  Profiles (remainder) pressed into: TIGRFAMs_15.0.hmm.h3p

Command error:
  [10:45:53] This is prokka 1.14.6
  [10:45:53] Written by Torsten Seemann <torsten.seemann@gmail.com>
  [10:45:53] Homepage is https://github.com/tseemann/prokka
  [10:45:53] Local time is Mon Sep 11 10:45:53 2023
  [10:45:53] You are not telling me who you are!
  [10:45:53] Operating system is linux
  [10:45:53] You have BioPerl 1.7.8
  Argument "1.7.8" isn't numeric in numeric lt (<) at /usr/local/bin/prokka line 259.
  [10:45:53] System has 12 cores.
  [10:45:53] Will use maximum of 4 cores.
  [10:45:53] Annotating as >>> Bacteria <<<
  [10:45:53] 'cleaned_header.fasta' is not a readable non-empty FASTA file

Work dir:
  /home/jfrancisco/work/f5/d75e1f5b0246d17396f7a91410b6e7

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
`
How can I solve that prokka´s problem ?
Thanks

**Comment by fmalmeida** [comment]
``Hello hello,

The problem seems to be with the FASTA file ("'cleaned_header.fasta' is not a readable non-empty FASTA file")

Can you check both the files:

* /home/jfrancisco/work/f5/d75e1f5b0246d17396f7a91410b6e7/cleaned_header.fasta

The command line for it seems to be missing the input FASTA to be cleaned, see:

# clean headers char limit
  awk '{ if ($0 ~ />/) print substr($0,1,21) ; else print $0 }'  > cleaned_header.fasta

Can you check if the samplesheet is proper and it has access to all FASTA files?

I am also launching a run with the testing profile right now to try it as I have to finalise the tests to make a release.

Finally, since this is a testing run, just to make sure dev is proper for a release, I advise to not execute many samples with a testing/developing branch. Thus, I would be advising to execute it with only one to three samples.

**Comment by fmalmeida** [comment]
My testing run is working fine. Maybe it is something with the samplesheet or input file.

**Comment by fmalmeida** [comment]
You can also try it, just to check if it works, instead of using `--input` you use `-profile test,docker`

**Comment by fmalmeida** [comment]
#30 will stay out of release

Last thing needed is updating the documentation

**Comment by fmalmeida** [comment]
#93  merged
